/** Momentum generated by playbook lines and spent on Bonus Time. */

import { activationAttackIndices } from '@/core/attackRows';
import { BONUS_TIME_MOMENTUM_COST } from '@/core/constants';
import { effectiveDamageForChoice } from '@/core/damage';
import { getPlaybookResult } from '@/core/wrapSlots';
import type { AttackerData } from '@/types/core/attacker';
import type {
  MomentousLineStyle,
  PlaybookChoiceId,
  PlaybookDamageMods,
  WrapPick,
} from '@/types/core/playbook';

export const momentousLineStyle = (
  attacker: AttackerData,
  id: PlaybookChoiceId,
  mods: PlaybookDamageMods,
): MomentousLineStyle => {
  const r = getPlaybookResult(attacker, id);

  if (r.momentum !== true) {
    return 'none';
  }

  return effectiveDamageForChoice(attacker, id, mods) > 0 ? 'heat' : 'zeroed';
};

/**
 * True when this pick earns momentum on a hit: momentous on the card **and**
 * effective damage greater than 0 (same rule as the red playbook chip; Tough Hide can zero it out).
 */
export const pickGeneratesMomentum = (
  attacker: AttackerData,
  id: WrapPick | null | undefined,
  mods: PlaybookDamageMods,
): boolean => {
  if (id == null) {
    return false;
  }

  return momentousLineStyle(attacker, id, mods) === 'heat';
};

const bonusTimeSpent = (
  attackIndex: number,
  bonusTimeByAttack: readonly boolean[],
): boolean => {
  return bonusTimeByAttack[attackIndex] === true;
};

/**
 * Momentum available **before** this attack’s roll (after prior attacks’ heat
 * picks and their Bonus Time spends, not including this attack’s wrap or spend).
 */
export const momentumPoolBeforeBonusTime = (
  attacker: AttackerData,
  wrapPicks: WrapPick[][],
  damageMods: PlaybookDamageMods,
  attackIndex: number,
  startingMomentum: number,
  bonusTimeByAttack: readonly boolean[],
  activeBaseCount: number,
): number => {
  const order = activationAttackIndices(
    attacker,
    wrapPicks,
    damageMods,
    activeBaseCount,
  );

  const pos = order.indexOf(attackIndex);

  if (pos < 0) {
    return startingMomentum;
  }

  let total = startingMomentum;

  for (let oi = 0; oi < pos; oi++) {
    const j = order[oi];
    const row = wrapPicks[j];

    if (row?.length) {
      for (const id of row) {
        if (pickGeneratesMomentum(attacker, id, damageMods)) {
          total += 1;
        }
      }
    }

    if (bonusTimeSpent(j, bonusTimeByAttack)) {
      total -= 1;
    }
  }

  return total;
};

/**
 * Total momentum after this attack in activation order: starting momentum,
 * plus heat picks through this attack, minus Bonus Time spends through this attack.
 * Earned momentum is not capped at 20.
 */
export const momentumAfterAttackInclusive = (
  attacker: AttackerData,
  wrapPicks: WrapPick[][],
  damageMods: PlaybookDamageMods,
  attackIndex: number,
  startingMomentum: number,
  bonusTimeByAttack: readonly boolean[],
  activeBaseCount: number,
): number => {
  const order = activationAttackIndices(
    attacker,
    wrapPicks,
    damageMods,
    activeBaseCount,
  );

  const pos = order.indexOf(attackIndex);

  if (pos < 0) {
    return startingMomentum;
  }

  let total = startingMomentum;

  for (let oi = 0; oi <= pos; oi++) {
    const j = order[oi];
    const row = wrapPicks[j];

    if (row?.length) {
      for (const id of row) {
        if (pickGeneratesMomentum(attacker, id, damageMods)) {
          total += 1;
        }
      }
    }

    if (bonusTimeSpent(j, bonusTimeByAttack)) {
      total -= 1;
    }
  }

  return total;
};

/** Passes beyond one per swing, as a safety margin for the settle loop. */
const EXTRA_SETTLE_PASSES = 2;

/** Clears Bonus Time flags that can no longer be paid (pool less than 1 before that swing). */
export const sanitizeBonusTimeFlags = (
  attacker: AttackerData,
  wrapPicks: WrapPick[][],
  damageMods: PlaybookDamageMods,
  startingMomentum: number,
  bonusTimeByAttack: readonly boolean[],
  activeBaseCount: number,
): boolean[] => {
  const order = activationAttackIndices(
    attacker,
    wrapPicks,
    damageMods,
    activeBaseCount,
  );

  const next = bonusTimeByAttack.map((b) => b);

  const maxPasses = order.length + EXTRA_SETTLE_PASSES;

  for (let pass = 0; pass < maxPasses; pass++) {
    let changed = false;

    for (const i of order) {
      if (!next[i]) {
        continue;
      }

      const pool = momentumPoolBeforeBonusTime(
        attacker,
        wrapPicks,
        damageMods,
        i,
        startingMomentum,
        next,
        activeBaseCount,
      );

      if (pool < BONUS_TIME_MOMENTUM_COST) {
        next[i] = false;
        changed = true;
      }
    }

    if (!changed) {
      break;
    }
  }

  return next;
};
